#!/usr/bin/env python3
'''An extremely annoying program modeled after the meme'''

import colors as c

try:

    while True:
        print(c.random() + "🐱 Nyan" + c.x, end=" " )

except KeyboardInterrupt:
    print("Awwww man. 🎩")
