#!/usr/bin/env python3
'''A simple program to print a colorful greeting'''

import colors as c 

def say_hello():
    print(c.clear + c.Y + "Hello " + c.O + "world!" + c.X)

def say_colorful_hello():
    print(c.clear + c.multi("Hello world!") + c.X)

#say_hello()
say_colorful_hello()

