#!/usr/bin/env python3

import sys
import colors as c

# this is a tuple, (an unchangable list)
negative = ("no", "nuhuh","i don't like")

def assert_likes(food="pizza rolls"):
    print(c.clear + c.random() + "Do you like " + food + "?" + c.x)
    answer = input(c.base00 + "> " + c.base3)
    answer = answer.lower().strip()
    if answer.startswith(negative): 
        print(c.red + "Well fine." + c.x)
        sys.exit()

assert_likes() # default
assert_likes("waffles")
assert_likes("pancakes")
assert_likes("french toast")

print(c.clear + "♫ Doo, doo doo doot ♫")
call(["say","Doo, doo doo doot"])

print(c.clear + "♫ Can't wait to get a mouthful! ♫")
call(["say","Can't wait to get a mouthful!"])


