#!/usr/bin/env python3
"""A cordial exchange"""

import colors as c
from emoji import smiley

print(c.clear + c.blue + "Hi there, what’s your name?")
name = input(c.base00 + "> " + c.base3)
print(c.yellow + "Nice to meet you, " + name + "! " + smiley)

