#!/usr/bin/env python3
'''A simple program to print a colorful greeting'''

def say_hello():
    import colors as c 
    print(c.clear + c.Y + "Hello " + c.O + "world!" + c.X)

if __name__ == "__main__":
    say_hello()

