#!/usr/bin/env python3

import colors as c

print(c.base01 + "Do you like waffles?")
answer = input(c.cyan + "> " + c.base3)

if "yes" in answer.lower().strip():
    print(c.base01 + "Do you like pancakes?")
else:
    print("Fine, but I do.")
    exit()
